"""精灵稳定档案、物种外貌配置和解析接口。"""

from .canon import (
    ELFARIA_CANON,
    SPECIES_CANON_VERSION,
    WORLD_CANON_VERSION,
    SpeciesCanon,
    WorldCanon,
    get_species_canon,
    get_species_canon_for_technical_id,
    list_species_canons,
)
from .generator import AppearanceGenerator, create_visual_profile
from .models import (
    SUPPORTED_MORPHOLOGIES,
    AppearanceGenome,
    ElfieIdentity,
    ElfieOrigin,
    ElfieProfile,
    EmbodimentProfile,
    ProfileProvenance,
    RegionAccent,
)
from .port import ProfileStorePort
from .resolver import AppearanceResolver, ResolvedAppearance
from .species import (
    APPEARANCE_REGION_IDS,
    AppearanceMarkingRule,
    AppearanceRegionRecipe,
    AppearanceRegionRule,
    CorrelationWeights,
    Distribution,
    RegionAccentSpec,
    ScaleRange,
    SpeciesAppearanceProfile,
    get_species_profile,
)
from .species_registry import (
    SPECIES_REGISTRY,
    SUPPORTED_SPECIES,
    SpeciesCatalog,
    SpeciesDefinition,
    SpeciesGenesisProfile,
    SpeciesPresentationImages,
    SpeciesStatus,
    configure_species_catalog,
    current_species_catalog,
    get_species_definition,
    list_species_definitions,
    validate_species_registry,
)

__all__ = [
    "AppearanceGenerator",
    "AppearanceGenome",
    "RegionAccent",
    "AppearanceResolver",
    "ELFARIA_CANON",
    "ElfieOrigin",
    "EmbodimentProfile",
    "ElfieIdentity",
    "ElfieProfile",
    "ProfileStorePort",
    "ProfileProvenance",
    "ResolvedAppearance",
    "SUPPORTED_MORPHOLOGIES",
    "SUPPORTED_SPECIES",
    "CorrelationWeights",
    "Distribution",
    "APPEARANCE_REGION_IDS",
    "AppearanceMarkingRule",
    "AppearanceRegionRecipe",
    "AppearanceRegionRule",
    "RegionAccentSpec",
    "ScaleRange",
    "SPECIES_CANON_VERSION",
    "WORLD_CANON_VERSION",
    "SpeciesCanon",
    "SpeciesAppearanceProfile",
    "SpeciesCatalog",
    "SpeciesDefinition",
    "SpeciesGenesisProfile",
    "SpeciesPresentationImages",
    "SpeciesStatus",
    "SPECIES_REGISTRY",
    "WorldCanon",
    "configure_species_catalog",
    "current_species_catalog",
    "create_visual_profile",
    "get_species_profile",
    "get_species_canon",
    "get_species_canon_for_technical_id",
    "get_species_definition",
    "list_species_canons",
    "list_species_definitions",
    "validate_species_registry",
]
