import type { OwnerElfie, OwnerUser } from "../api/client"

export const MOCK_USERS: readonly OwnerUser[] = [
  {
    user_id: 1,
    account_id: "admin123",
    role: "owner",
    created_at: "2026-06-30 13:40:35",
    gender: "男",
    birth_date: "1971-09-15",
    elfie_count: 1,
    display_name: "管理员",
    elfie_quota_override: null,
    effective_elfie_limit: 3,
    presence: "online",
    last_seen_at: null,
    language: "zh-CN",
    avatar_url: null,
  },
  {
    user_id: 2,
    account_id: "user123",
    role: "user",
    created_at: "2026-07-01 09:12:00",
    gender: "女",
    birth_date: "1992-04-18",
    elfie_count: 1,
    display_name: "用户示例",
    elfie_quota_override: 2,
    effective_elfie_limit: 2,
    presence: "offline",
    last_seen_at: null,
    language: "zh-CN",
    avatar_url: null,
  },
]

export const MOCK_ELFIES: readonly OwnerElfie[] = [
  {
    elfie_id: "12345678",
    owner: { user_id: 1, account_id: "admin123", display_name: "管理员" },
    profile: {
      elfie_id: "12345678",
      name: "Happy",
      species_id: "fox",
      gender: "未登记",
      birth_date: "2026-06-01",
      summary: "一只活泼好动、精力旺盛的小精灵。",
      online_status: "online",
      status: { code: "awake", label: "在线", tone: "active" },
      portrait_url: "",
      appearance: {},
      big_five: { openness: 0.8, conscientiousness: 0.6, extraversion: 0.8, agreeableness: 0.7, neuroticism: 0.2 },
      personality_tags: ["活泼", "亲人"],
      nest: { room_name: "主巢", bed_name: "床位 1", posture: "standing" },
      embodiment: { state: "awake" },
    },
    food_policy: { main_food_id: "food_common", effective_main_food_id: "food_common", main_food_options: [{ food_id: "food_common", display_name: "常用粮" }], main_food_unavailable: false },
    created_at: "2026-06-30 13:45:00",
  },
  {
    elfie_id: "23456789",
    owner: { user_id: 2, account_id: "user123", display_name: "用户示例" },
    profile: {
      elfie_id: "23456789",
      name: "Kettle",
      species_id: "fox",
      gender: "未登记",
      birth_date: null,
      summary: "安静、好奇，喜欢观察巢里的每一个角落。",
      online_status: "offline",
      status: { code: "sleeping", label: "休息中", tone: "muted" },
      portrait_url: "",
      appearance: {},
      big_five: { openness: 0.7, conscientiousness: 0.8, extraversion: 0.3, agreeableness: 0.8, neuroticism: 0.2 },
      personality_tags: ["安静", "好奇"],
      nest: { room_name: "主巢", bed_name: "床位 2", posture: "sleeping" },
      embodiment: { state: "sleeping" },
    },
    food_policy: { main_food_id: "food_common", effective_main_food_id: "food_common", main_food_options: [{ food_id: "food_common", display_name: "常用粮" }], main_food_unavailable: false },
    created_at: "2026-07-01 09:18:00",
  },
]
