"""Stable public facade and models for Runtime lifecycle orchestration."""

from app.orchestration.lifecycle.capability_gate import (
    DEFAULT_CAPABILITY_REQUIREMENTS,
    CapabilityDeniedError,
    CapabilityPermit,
    CapabilityRequirement,
    CapabilityRequirementRegistry,
)
from app.orchestration.lifecycle.commands import (
    DEFAULT_GODOT_WS_PORT,
    DEFAULT_HTTP_PORT,
    DEFAULT_SERVICE_PORTS,
    MANAGED_START_ENV,
    command_runs_service,
    http_port_from_command,
    service_ports_from_command,
    validate_service_ports,
)
from app.orchestration.lifecycle.facade import LifecycleFacade, RuntimeLifecycle
from app.orchestration.lifecycle.ports import (
    AuthorityHostConfig,
    DataHomeInspection,
    DataHomeRecoveryResult,
    DataHomeState,
    DoctorRepairResult,
    DoctorValidationResult,
    ServicePortStatus,
    UninstallState,
)
from app.orchestration.lifecycle.runtime_snapshot import (
    BackendTier,
    ComponentSnapshot,
    ComponentState,
    EndpointSnapshot,
    FailureSnapshot,
    ModelHealthProjection,
    ModelOverallState,
    OwnerLease,
    RuntimeComponent,
    RuntimeObservation,
    RuntimePhase,
    RuntimeProgressPhase,
    RuntimeProjectionV1,
    RuntimeSnapshotV1,
    RuntimeTarget,
)
from app.orchestration.lifecycle.types import (
    DataHomeRecoveryError,
    FrontendPreparationError,
    LaunchFailedError,
    RecoveryInProgressError,
    ServiceLifecycleResult,
    ServicePortsActiveError,
)
from app.orchestration.lifecycle.world_worker import RuntimeWorldWorker

__all__ = [
    "AuthorityHostConfig",
    "CapabilityDeniedError",
    "CapabilityPermit",
    "CapabilityRequirement",
    "CapabilityRequirementRegistry",
    "DEFAULT_CAPABILITY_REQUIREMENTS",
    "DataHomeInspection",
    "DataHomeRecoveryError",
    "DataHomeRecoveryResult",
    "DataHomeState",
    "BackendTier",
    "ComponentSnapshot",
    "ComponentState",
    "DEFAULT_GODOT_WS_PORT",
    "DEFAULT_HTTP_PORT",
    "DEFAULT_SERVICE_PORTS",
    "DoctorRepairResult",
    "DoctorValidationResult",
    "FrontendPreparationError",
    "LaunchFailedError",
    "LifecycleFacade",
    "MANAGED_START_ENV",
    "EndpointSnapshot",
    "FailureSnapshot",
    "ModelHealthProjection",
    "ModelOverallState",
    "OwnerLease",
    "RecoveryInProgressError",
    "RuntimeComponent",
    "RuntimeObservation",
    "RuntimePhase",
    "RuntimeProgressPhase",
    "RuntimeProjectionV1",
    "RuntimeSnapshotV1",
    "RuntimeTarget",
    "RuntimeWorldWorker",
    "RuntimeLifecycle",
    "ServiceLifecycleResult",
    "ServicePortStatus",
    "ServicePortsActiveError",
    "UninstallState",
    "command_runs_service",
    "http_port_from_command",
    "service_ports_from_command",
    "validate_service_ports",
]
