"""Public facade for system Operations."""

from .errors import (
    DatabaseMaintenanceRejected,
    OperationsError,
    OperationsForbidden,
    OperationsUnavailable,
)
from .models import (
    ActiveSessionResult,
    ActiveSessionsResult,
    BackupDatabasesCommand,
    DatabaseBackupResult,
    GetMobileAccessQuery,
    GetRuntimeStatusQuery,
    GetUsageStatsQuery,
    ListActiveSessionsQuery,
    ListTableCountsQuery,
    MobileAccessResult,
    ResetDatabasesCommand,
    RuntimeEventResult,
    RuntimeEventStatus,
    RuntimeEventType,
    RuntimeMetadataEntry,
    RuntimeMetadataValue,
    RuntimeObserverResult,
    RuntimeStatusResult,
    SpeciesCountResult,
    TableCountResult,
    TableCountsResult,
    UsageStatsResult,
)
from .port_models import (
    StoredActiveSession,
    StoredDatabaseBackup,
    StoredRuntimeEvent,
    StoredRuntimeMetadata,
    StoredRuntimeSnapshot,
    StoredSpeciesCount,
    StoredTableCount,
    StoredUsageStats,
)
from .ports import (
    DatabaseMaintenancePort,
    NetworkAccessProjectionPort,
    OperationsPortDatabaseMissing,
    OperationsPortError,
    OperationsPortUnsafeTarget,
    OperationsProjectionPort,
    RuntimeObserverProjectionPort,
)
from .service import OperationsFacade

__all__ = (
    "ActiveSessionResult",
    "ActiveSessionsResult",
    "BackupDatabasesCommand",
    "DatabaseBackupResult",
    "DatabaseMaintenancePort",
    "DatabaseMaintenanceRejected",
    "GetMobileAccessQuery",
    "GetRuntimeStatusQuery",
    "GetUsageStatsQuery",
    "ListActiveSessionsQuery",
    "ListTableCountsQuery",
    "MobileAccessResult",
    "NetworkAccessProjectionPort",
    "OperationsError",
    "OperationsFacade",
    "OperationsForbidden",
    "OperationsPortDatabaseMissing",
    "OperationsPortError",
    "OperationsPortUnsafeTarget",
    "OperationsProjectionPort",
    "OperationsUnavailable",
    "ResetDatabasesCommand",
    "RuntimeEventResult",
    "RuntimeEventStatus",
    "RuntimeEventType",
    "RuntimeMetadataEntry",
    "RuntimeMetadataValue",
    "RuntimeObserverProjectionPort",
    "RuntimeObserverResult",
    "RuntimeStatusResult",
    "SpeciesCountResult",
    "StoredActiveSession",
    "StoredDatabaseBackup",
    "StoredRuntimeEvent",
    "StoredRuntimeMetadata",
    "StoredRuntimeSnapshot",
    "StoredSpeciesCount",
    "StoredTableCount",
    "StoredUsageStats",
    "TableCountResult",
    "TableCountsResult",
    "UsageStatsResult",
)
