"""Public facade for system Operations."""

from .errors import (
    DatabaseMaintenanceRejected,
    OperationsError,
    OperationsForbidden,
    OperationsUnavailable,
)
from .models import (
    ActiveSessionResult,
    ActiveSessionsResult,
    BackupDatabasesCommand,
    DatabaseBackupResult,
    GetMobileAccessQuery,
    GetRuntimeStatusQuery,
    GetUsageStatsQuery,
    ListActiveSessionsQuery,
    ListTableCountsQuery,
    MobileAccessResult,
    ModelExecutionEventResult,
    ModelExecutionEventStatus,
    ModelExecutionEventType,
    ModelExecutionMetadataEntry,
    ModelExecutionMetadataValue,
    ModelExecutionObserverResult,
    ResetDatabasesCommand,
    RuntimeStatusResult,
    SpeciesCountResult,
    TableCountResult,
    TableCountsResult,
    UsageStatsResult,
)
from .port_models import (
    StoredActiveSession,
    StoredDatabaseBackup,
    StoredModelExecutionEvent,
    StoredModelExecutionMetadata,
    StoredModelExecutionSnapshot,
    StoredSpeciesCount,
    StoredTableCount,
    StoredUsageStats,
)
from .ports import (
    DatabaseMaintenancePort,
    ModelExecutionObserverProjectionPort,
    NetworkAccessProjectionPort,
    OperationsPortDatabaseMissing,
    OperationsPortError,
    OperationsPortUnsafeTarget,
    OperationsProjectionPort,
)
from .service import OperationsFacade

__all__ = (
    "ActiveSessionResult",
    "ActiveSessionsResult",
    "BackupDatabasesCommand",
    "DatabaseBackupResult",
    "DatabaseMaintenancePort",
    "DatabaseMaintenanceRejected",
    "GetMobileAccessQuery",
    "GetRuntimeStatusQuery",
    "GetUsageStatsQuery",
    "ListActiveSessionsQuery",
    "ListTableCountsQuery",
    "MobileAccessResult",
    "NetworkAccessProjectionPort",
    "OperationsError",
    "OperationsFacade",
    "OperationsForbidden",
    "OperationsPortDatabaseMissing",
    "OperationsPortError",
    "OperationsPortUnsafeTarget",
    "OperationsProjectionPort",
    "OperationsUnavailable",
    "ResetDatabasesCommand",
    "ModelExecutionEventResult",
    "ModelExecutionEventStatus",
    "ModelExecutionEventType",
    "ModelExecutionMetadataEntry",
    "ModelExecutionMetadataValue",
    "ModelExecutionObserverProjectionPort",
    "ModelExecutionObserverResult",
    "RuntimeStatusResult",
    "SpeciesCountResult",
    "StoredActiveSession",
    "StoredDatabaseBackup",
    "StoredModelExecutionEvent",
    "StoredModelExecutionMetadata",
    "StoredModelExecutionSnapshot",
    "StoredSpeciesCount",
    "StoredTableCount",
    "StoredUsageStats",
    "TableCountResult",
    "TableCountsResult",
    "UsageStatsResult",
)
