"""Stable public facade for Adoption."""

from .errors import (
    AdoptionCandidateNotAccepted,
    AdoptionCandidateSetExpired,
    AdoptionCapacityReached,
    AdoptionError,
    AdoptionInvalid,
    AdoptionNestCapacityReached,
    AdoptionOwnerNotFound,
    AdoptionSessionBusy,
    AdoptionUnavailable,
)
from .facade import AdoptionService
from .models import (
    AcceptedAdoptionReservation,
    AdoptionNestCapacity,
    AdoptionOptionsResult,
    AdoptionQuota,
    AdoptionSpecies,
    AdoptionSpeciesImage,
    AdoptionSpeciesImages,
    CandidateAppearance,
    CandidateRepliesResult,
    CandidateReplyResult,
    CandidateResult,
    CandidateReveal,
    CandidateSetResult,
    CreateCandidateSetCommand,
    GetAdoptionOptionsQuery,
    ReplyToCandidatesCommand,
    ReserveAcceptedAdoptionCommand,
    SpeciesId,
    SpeciesImageKind,
)
from .port_models import (
    AdoptionNestCapacityRecord,
    AdoptionPolicyRecord,
    AdoptionQuotaRecord,
    AdoptionReservationRecord,
)
from .ports import (
    AdoptionNarrativePort,
    AdoptionPersistencePort,
    AdoptionPolicyPort,
    AdoptionPortCapacityReached,
    AdoptionPortError,
    AdoptionPortNestCapacityReached,
    AdoptionPortOwnerNotFound,
    CandidatePortraitPort,
    SpeciesPresentationPort,
)

__all__ = (
    "AcceptedAdoptionReservation",
    "AdoptionSpecies",
    "AdoptionCandidateNotAccepted",
    "AdoptionCandidateSetExpired",
    "AdoptionCapacityReached",
    "AdoptionError",
    "AdoptionInvalid",
    "AdoptionNestCapacity",
    "AdoptionSpeciesImage",
    "AdoptionSpeciesImages",
    "AdoptionNestCapacityReached",
    "AdoptionNestCapacityRecord",
    "AdoptionOptionsResult",
    "AdoptionOwnerNotFound",
    "AdoptionSessionBusy",
    "AdoptionPersistencePort",
    "AdoptionNarrativePort",
    "AdoptionPolicyPort",
    "AdoptionPolicyRecord",
    "AdoptionPortCapacityReached",
    "AdoptionPortError",
    "AdoptionPortNestCapacityReached",
    "AdoptionPortOwnerNotFound",
    "AdoptionQuota",
    "AdoptionQuotaRecord",
    "AdoptionReservationRecord",
    "AdoptionService",
    "AdoptionUnavailable",
    "CandidateAppearance",
    "CandidateRepliesResult",
    "CandidateReplyResult",
    "CandidateReveal",
    "CandidateResult",
    "CandidateSetResult",
    "CandidatePortraitPort",
    "SpeciesPresentationPort",
    "SpeciesImageKind",
    "CreateCandidateSetCommand",
    "GetAdoptionOptionsQuery",
    "ReplyToCandidatesCommand",
    "ReserveAcceptedAdoptionCommand",
    "SpeciesId",
)
