"""Machine-readable links between architecture contracts and their enforcement."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple


@dataclass(frozen=True)
class ContractRegistration:
    """One logical bilingual contract and the artifacts that enforce it."""

    contract_id: str
    version: str
    english_path: str
    chinese_path: str
    decision_paths: Tuple[str, ...]
    agent_paths: Tuple[str, ...]
    scanner_paths: Tuple[str, ...]
    test_paths: Tuple[str, ...]
    conformance_paths: Tuple[str, ...] = ()
    baseline_path: Optional[str] = None


CONTRACT_REGISTRY: Tuple[ContractRegistration, ...] = (
    ContractRegistration(
        contract_id="repository-governance",
        version="1.9",
        english_path="docs/developer/contracts/repository-governance.md",
        chinese_path="docs/zh/developer/contracts/repository-governance.md",
        decision_paths=(
            "docs/developer/decisions/0003-architecture-governance-ratchet.md",
            "docs/zh/developer/decisions/0003-architecture-governance-ratchet.md",
            "docs/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/zh/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/developer/decisions/0010-desktop-authority-host-structure.md",
            "docs/zh/developer/decisions/0010-desktop-authority-host-structure.md",
            "docs/developer/decisions/0011-repository-wide-change-classification.md",
            "docs/zh/developer/decisions/0011-repository-wide-change-classification.md",
            "docs/developer/decisions/0012-effective-dependency-targets.md",
            "docs/zh/developer/decisions/0012-effective-dependency-targets.md",
            "docs/developer/decisions/0015-evidence-backed-cleanup-closure.md",
            "docs/zh/developer/decisions/0015-evidence-backed-cleanup-closure.md",
            "docs/developer/decisions/0023-tiered-validation-and-reuse.md",
            "docs/zh/developer/decisions/0023-tiered-validation-and-reuse.md",
        ),
        agent_paths=(
            "AGENTS.md",
            "docs/AGENTS.md",
            "scripts/architecture/AGENTS.md",
            "test/architecture/AGENTS.md",
        ),
        scanner_paths=(
            "scripts/architecture/check_governance_change.py",
            "scripts/architecture/effective_dependency_python.py",
            "scripts/architecture/effective_dependency_scan.py",
            "scripts/architecture/effective_dependency_targets.py",
            "scripts/architecture/effective_dependency_text.py",
            "scripts/architecture/structural_scope_scan.py",
            "scripts/architecture/validation_cache.py",
            "scripts/architecture/validation_gate.py",
            "scripts/architecture/validation_plan.py",
        ),
        test_paths=(
            "test/architecture/test_architecture_governance.py",
            "test/architecture/test_app_layer_boundaries.py",
            "test/architecture/test_effective_dependency_boundaries.py",
            "test/architecture/test_system_layer_boundaries.py",
            "test/architecture/test_validation_gate.py",
        ),
    ),
    ContractRegistration(
        contract_id="documentation-structure",
        version="1.1",
        english_path="docs/developer/contracts/documentation-structure.md",
        chinese_path="docs/zh/developer/contracts/documentation-structure.md",
        decision_paths=(
            "docs/developer/decisions/0008-documentation-information-architecture.md",
            "docs/zh/developer/decisions/0008-documentation-information-architecture.md",
        ),
        agent_paths=("docs/AGENTS.md",),
        scanner_paths=(),
        test_paths=("test/architecture/test_documentation_structure.py",),
    ),
    ContractRegistration(
        contract_id="system-architecture",
        version="1.9",
        english_path="docs/developer/contracts/system.md",
        chinese_path="docs/zh/developer/contracts/system.md",
        decision_paths=(
            "docs/developer/decisions/0002-system-ports-adapters.md",
            "docs/zh/developer/decisions/0002-system-ports-adapters.md",
            "docs/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/zh/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/developer/decisions/0010-desktop-authority-host-structure.md",
            "docs/zh/developer/decisions/0010-desktop-authority-host-structure.md",
            "docs/developer/decisions/0012-effective-dependency-targets.md",
            "docs/zh/developer/decisions/0012-effective-dependency-targets.md",
            "docs/developer/decisions/0013-nest-godot-semantic-world-boundary.md",
            "docs/zh/developer/decisions/0013-nest-godot-semantic-world-boundary.md",
            "docs/developer/decisions/0016-nest-persistence-port-ownership.md",
            "docs/zh/developer/decisions/0016-nest-persistence-port-ownership.md",
            "docs/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/zh/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/developer/decisions/0021-authoritative-service-lifecycle.md",
            "docs/zh/developer/decisions/0021-authoritative-service-lifecycle.md",
        ),
        agent_paths=(
            "elfie/AGENTS.md",
            "nest/AGENTS.md",
            "infrastructure/AGENTS.md",
            "infrastructure/persistence/AGENTS.md",
            "infrastructure/godot/AGENTS.md",
            "godot_project/AGENTS.md",
        ),
        scanner_paths=(
            "scripts/architecture/database_change_inventory.py",
            "scripts/architecture/database_change_scan.py",
            "scripts/architecture/effective_dependency_python.py",
            "scripts/architecture/effective_dependency_scan.py",
            "scripts/architecture/effective_dependency_targets.py",
            "scripts/architecture/effective_dependency_text.py",
            "scripts/architecture/system_layer_scan.py",
        ),
        test_paths=(
            "test/architecture/test_effective_dependency_boundaries.py",
            "test/architecture/test_system_layer_boundaries.py",
            "test/architecture/test_project_structure.py",
            "test/architecture/test_elfie_cognitive_contracts.py",
            "test/architecture/test_gateway_runtime_boundaries.py",
            "test/architecture/test_runtime_import_boundaries.py",
            "test/architecture/test_system_ports_contract.py",
            "test/architecture/test_runtime_observer_contracts.py",
            "test/architecture/test_database_change_boundaries.py",
            "test/architecture/test_storage_boundaries.py",
        ),
    ),
    ContractRegistration(
        contract_id="service-lifecycle",
        version="1.0",
        english_path="docs/developer/contracts/service-lifecycle.md",
        chinese_path="docs/zh/developer/contracts/service-lifecycle.md",
        decision_paths=(
            "docs/developer/decisions/0021-authoritative-service-lifecycle.md",
            "docs/zh/developer/decisions/0021-authoritative-service-lifecycle.md",
        ),
        agent_paths=(
            "AGENTS.md",
            "app/AGENTS.md",
            "app/bootstrap/AGENTS.md",
            "app/interfaces/cli/AGENTS.md",
            "app/interfaces/desktop/AGENTS.md",
            "app/orchestration/AGENTS.md",
            "app/orchestration/lifecycle/AGENTS.md",
            "infrastructure/AGENTS.md",
            "infrastructure/godot/AGENTS.md",
        ),
        scanner_paths=(),
        test_paths=("test/architecture/test_service_lifecycle_contract.py",),
        conformance_paths=(
            "docs/developer/conformance/service-lifecycle.md",
            "docs/zh/developer/conformance/service-lifecycle.md",
        ),
    ),
    ContractRegistration(
        contract_id="configuration-management",
        version="1.2",
        english_path="docs/developer/contracts/configuration-management.md",
        chinese_path="docs/zh/developer/contracts/configuration-management.md",
        decision_paths=(
            "docs/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/zh/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/developer/decisions/0020-configuration-driven-species-packages.md",
            "docs/zh/developer/decisions/0020-configuration-driven-species-packages.md",
        ),
        agent_paths=(
            "AGENTS.md",
            "app/bootstrap/AGENTS.md",
            "app/features/configuration/AGENTS.md",
            "infrastructure/AGENTS.md",
            "infrastructure/persistence/AGENTS.md",
        ),
        scanner_paths=("scripts/architecture/check_governance_change.py",),
        test_paths=(
            "test/architecture/test_architecture_governance.py",
            "test/architecture/test_configuration_management.py",
        ),
        conformance_paths=(
            "docs/developer/conformance/configuration-management.md",
            "docs/zh/developer/conformance/configuration-management.md",
        ),
    ),
    ContractRegistration(
        contract_id="nest-godot-semantic-world",
        version="1.1",
        english_path="docs/developer/contracts/nest-godot-semantic-world.md",
        chinese_path="docs/zh/developer/contracts/nest-godot-semantic-world.md",
        decision_paths=(
            "docs/developer/decisions/0013-nest-godot-semantic-world-boundary.md",
            "docs/zh/developer/decisions/0013-nest-godot-semantic-world-boundary.md",
            "docs/developer/decisions/0015-evidence-backed-cleanup-closure.md",
            "docs/zh/developer/decisions/0015-evidence-backed-cleanup-closure.md",
            "docs/developer/decisions/0016-nest-persistence-port-ownership.md",
            "docs/zh/developer/decisions/0016-nest-persistence-port-ownership.md",
        ),
        agent_paths=(
            "AGENTS.md",
            "nest/AGENTS.md",
            "app/orchestration/AGENTS.md",
            "infrastructure/godot/AGENTS.md",
            "godot_project/AGENTS.md",
        ),
        scanner_paths=(
            "scripts/architecture/structural_scope_scan.py",
            "scripts/architecture/system_layer_scan.py",
        ),
        test_paths=(
            "test/architecture/test_system_layer_boundaries.py",
            "test/architecture/test_gateway_runtime_boundaries.py",
            "test/architecture/test_runtime_observer_contracts.py",
        ),
        conformance_paths=(
            "docs/developer/conformance/nest-godot-semantic-world.md",
            "docs/zh/developer/conformance/nest-godot-semantic-world.md",
        ),
    ),
    ContractRegistration(
        contract_id="elfie-internal-architecture",
        version="2.0",
        english_path="docs/developer/contracts/elfie.md",
        chinese_path="docs/zh/developer/contracts/elfie.md",
        decision_paths=(
            "docs/developer/decisions/0005-elfie-internal-ports-adapters.md",
            "docs/zh/developer/decisions/0005-elfie-internal-ports-adapters.md",
            "docs/developer/decisions/0006-elfie-life-system-ownership.md",
            "docs/zh/developer/decisions/0006-elfie-life-system-ownership.md",
            "docs/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/zh/developer/decisions/0009-zero-debt-governance-closure.md",
        ),
        agent_paths=(
            "elfie/AGENTS.md",
            "elfie/brain/AGENTS.md",
            "elfie/brain/memory/AGENTS.md",
            "elfie/body/AGENTS.md",
            "elfie/communication/AGENTS.md",
            "elfie/nervous_system/AGENTS.md",
            "elfie/profile/AGENTS.md",
        ),
        scanner_paths=("scripts/architecture/system_layer_scan.py",),
        test_paths=("test/architecture/test_elfie_cognitive_contracts.py",),
        conformance_paths=(
            "docs/developer/conformance/elfie.md",
            "docs/zh/developer/conformance/elfie.md",
        ),
    ),
    ContractRegistration(
        contract_id="elfie-brain-internal-architecture",
        version="1.0",
        english_path="docs/developer/contracts/brain.md",
        chinese_path="docs/zh/developer/contracts/brain.md",
        decision_paths=(
            "docs/developer/decisions/0007-brain-turn-state-and-activity-ownership.md",
            "docs/zh/developer/decisions/0007-brain-turn-state-and-activity-ownership.md",
        ),
        agent_paths=("elfie/brain/AGENTS.md",),
        scanner_paths=(),
        test_paths=("test/architecture/test_elfie_brain_contract.py",),
    ),
    ContractRegistration(
        contract_id="application-architecture",
        version="1.9",
        english_path="docs/developer/contracts/application.md",
        chinese_path="docs/zh/developer/contracts/application.md",
        decision_paths=(
            "docs/developer/decisions/0001-lightweight-ports-adapters.md",
            "docs/zh/developer/decisions/0001-lightweight-ports-adapters.md",
            "docs/developer/decisions/0004-app-domain-slices.md",
            "docs/zh/developer/decisions/0004-app-domain-slices.md",
            "docs/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/zh/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/developer/decisions/0012-effective-dependency-targets.md",
            "docs/zh/developer/decisions/0012-effective-dependency-targets.md",
            "docs/developer/decisions/0016-nest-persistence-port-ownership.md",
            "docs/zh/developer/decisions/0016-nest-persistence-port-ownership.md",
            "docs/developer/decisions/0021-authoritative-service-lifecycle.md",
            "docs/zh/developer/decisions/0021-authoritative-service-lifecycle.md",
        ),
        agent_paths=(
            "app/AGENTS.md",
            "app/bootstrap/AGENTS.md",
            "app/features/AGENTS.md",
            "app/features/accounts/AGENTS.md",
            "app/features/configuration/AGENTS.md",
            "app/features/setup/AGENTS.md",
            "infrastructure/AGENTS.md",
            "infrastructure/devices/AGENTS.md",
            "infrastructure/persistence/AGENTS.md",
            "app/interfaces/AGENTS.md",
            "app/interfaces/api/AGENTS.md",
            "app/interfaces/cli/AGENTS.md",
            "app/interfaces/desktop/AGENTS.md",
            "app/interfaces/web/frontend/AGENTS.md",
            "app/orchestration/AGENTS.md",
            "app/orchestration/embodiment/AGENTS.md",
            "app/orchestration/lifecycle/AGENTS.md",
        ),
        scanner_paths=(
            "scripts/architecture/app_layer_scan.py",
            "scripts/architecture/effective_dependency_python.py",
            "scripts/architecture/effective_dependency_scan.py",
            "scripts/architecture/effective_dependency_targets.py",
            "scripts/architecture/effective_dependency_text.py",
        ),
        test_paths=(
            "test/architecture/test_app_layer_boundaries.py",
            "test/architecture/test_bootstrap_wiring_boundaries.py",
            "test/architecture/test_effective_dependency_boundaries.py",
            "test/architecture/test_runtime_import_boundaries.py",
            "test/architecture/test_storage_boundaries.py",
        ),
    ),
    ContractRegistration(
        contract_id="model-food-tool-behavior",
        version="1.8",
        english_path="docs/developer/contracts/model-food-tool-behavior.md",
        chinese_path="docs/zh/developer/contracts/model-food-tool-behavior.md",
        decision_paths=(
            "docs/developer/decisions/0002-system-ports-adapters.md",
            "docs/zh/developer/decisions/0002-system-ports-adapters.md",
            "docs/developer/decisions/0005-elfie-internal-ports-adapters.md",
            "docs/zh/developer/decisions/0005-elfie-internal-ports-adapters.md",
            "docs/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/zh/developer/decisions/0009-zero-debt-governance-closure.md",
            "docs/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/zh/developer/decisions/0017-bundled-defaults-and-user-configuration.md",
            "docs/developer/decisions/0019-provider-endpoint-availability.md",
            "docs/zh/developer/decisions/0019-provider-endpoint-availability.md",
        ),
        agent_paths=(
            "app/features/configuration/AGENTS.md",
            "elfie/AGENTS.md",
            "infrastructure/AGENTS.md",
        ),
        scanner_paths=(),
        test_paths=("test/architecture/test_model_food_tool_contract.py",),
        conformance_paths=(
            "docs/developer/conformance/provider-model-availability.md",
            "docs/zh/developer/conformance/provider-model-availability.md",
        ),
    ),
)


def registration_by_id(contract_id: str) -> ContractRegistration:
    """Return one registered logical contract."""

    for registration in CONTRACT_REGISTRY:
        if registration.contract_id == contract_id:
            return registration
    raise KeyError(contract_id)
