#!/bin/bash
# Install ElfieNest's repository-managed fast Git hook.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PRE_COMMIT_BIN="$PROJECT_ROOT/.venv/bin/pre-commit"
HOOK_TEMPLATE="$SCRIPT_DIR/git-hooks/pre-commit"

if ! git -C "$PROJECT_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Git hooks skipped: $PROJECT_ROOT is not a Git worktree."
    exit 0
fi

if [[ ! -x "$PRE_COMMIT_BIN" ]]; then
    echo "Missing repository pre-commit executable: $PRE_COMMIT_BIN" >&2
    echo "Run: bash scripts/bootstrap.sh ensure --tier=dev" >&2
    exit 1
fi
if [[ ! -x "$HOOK_TEMPLATE" ]]; then
    echo "Missing executable hook template: $HOOK_TEMPLATE" >&2
    exit 1
fi

HOOKS_DIR="$(git -C "$PROJECT_ROOT" rev-parse --path-format=absolute --git-path hooks)"
HOOK_PATH="$HOOKS_DIR/pre-commit"
LEGACY_BACKUP="$HOOKS_DIR/pre-commit.elfienest-legacy-backup"

mkdir -p "$HOOKS_DIR"

if [[ -f "$HOOK_PATH" ]] && \
    ! grep -Fq "File generated by pre-commit" "$HOOK_PATH" && \
    ! grep -Fq "ElfieNest managed pre-commit hook" "$HOOK_PATH"; then
    if [[ ! -e "$LEGACY_BACKUP" ]]; then
        cp -p "$HOOK_PATH" "$LEGACY_BACKUP"
        echo "Backed up the previous pre-commit hook to $LEGACY_BACKUP"
    else
        echo "Preserving the existing hook backup at $LEGACY_BACKUP"
    fi
fi

cd "$PROJECT_ROOT"
"$PRE_COMMIT_BIN" validate-config .pre-commit-config.yaml
"$PRE_COMMIT_BIN" install-hooks
install -m 0755 "$HOOK_TEMPLATE" "$HOOK_PATH"

if [[ ! -x "$HOOK_PATH" ]] || \
    ! grep -Fq "ElfieNest managed pre-commit hook" "$HOOK_PATH"; then
    echo "pre-commit did not install the expected managed hook at $HOOK_PATH" >&2
    exit 1
fi

echo "ElfieNest fast pre-commit hook is ready."
echo "Warm commits run staged diff, Gitleaks, and staged Python Ruff checks only."
