import type { RelationshipWorld } from "./model"

export const HAPPY_RELATIONSHIP_WORLD: RelationshipWorld = {
  nodes: [
    { id: "self", label: "Happy", kind: "self", weight: 1 },
    { id: "owner", label: "主人", kind: "human", weight: 0.98 },
    { id: "star", label: "星星", kind: "elfie", weight: 0.94 },
    { id: "moon", label: "月光", kind: "elfie", weight: 0.86 },
    { id: "mom", label: "妈妈", kind: "human", weight: 0.82 },
    { id: "admin", label: "管理员", kind: "human", weight: 0.78 },
    { id: "dad", label: "爸爸", kind: "human", weight: 0.74 },
    { id: "xiaoyu", label: "小雨", kind: "human", weight: 0.72 },
    { id: "alu", label: "阿洛", kind: "human", weight: 0.67 },
    { id: "doudou", label: "豆豆", kind: "elfie", weight: 0.64 },
    { id: "lin", label: "林老师", kind: "human", weight: 0.6 },
    { id: "mili", label: "米粒", kind: "elfie", weight: 0.57 },
    { id: "shop", label: "书店老板", kind: "human", weight: 0.53 },
    { id: "xiaohui", label: "小灰", kind: "elfie", weight: 0.5 },
    { id: "wang", label: "王阿姨", kind: "human", weight: 0.48 },
    { id: "tuantuan", label: "团团", kind: "elfie", weight: 0.45 },
    { id: "park", label: "公园管理员", kind: "human", weight: 0.4 },
    { id: "abu", label: "阿布", kind: "elfie", weight: 0.38 },
    { id: "cloud", label: "云端伙伴", kind: "human", weight: 0.36 },
    { id: "paopao", label: "泡泡", kind: "elfie", weight: 0.33 },
    { id: "xiaojv", label: "小橘", kind: "elfie", weight: 0.31 },
    { id: "yueyue", label: "月月", kind: "elfie", weight: 0.28 },
    { id: "neighbor", label: "邻居", kind: "human", weight: 0.25 },
    { id: "damao", label: "大毛", kind: "elfie", weight: 0.23 },
    { id: "tangtang", label: "糖糖", kind: "elfie", weight: 0.2 },
    { id: "garden", label: "花园精灵", kind: "elfie", weight: 0.17 },
    { id: "aunt", label: "陈阿姨", kind: "human", weight: 0.15 },
    { id: "xiaolan", label: "小蓝", kind: "human", weight: 0.14 },
    { id: "heihei", label: "黑黑", kind: "elfie", weight: 0.12 },
    { id: "beibei", label: "贝贝", kind: "elfie", weight: 0.1 },
  ],
  edges: [
    { source: "self", target: "owner", relationKey: "owner", displayLabel: "主人", weight: 1 },
    { source: "self", target: "star", relationKey: "friend", displayLabel: "朋友", weight: 0.9 },
    { source: "self", target: "moon", relationKey: "friend", displayLabel: "朋友", weight: 0.76 },
    { source: "self", target: "mom", relationKey: "family", displayLabel: "家人", weight: 0.74 },
    { source: "self", target: "admin", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.58 },
    { source: "self", target: "xiaoyu", relationKey: "friend", displayLabel: "朋友", weight: 0.68 },
    { source: "self", target: "alu", relationKey: "friend", displayLabel: "朋友", weight: 0.61 },
    { source: "self", target: "doudou", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.48 },
    { source: "self", target: "lin", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.42 },
    { source: "self", target: "shop", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.35 },
    { source: "self", target: "cloud", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.2 },
    { source: "owner", target: "star", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.92 },
    { source: "owner", target: "moon", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.85 },
    { source: "owner", target: "doudou", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.78 },
    { source: "owner", target: "mili", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.68 },
    { source: "owner", target: "xiaohui", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.56 },
    { source: "owner", target: "tuantuan", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.5 },
    { source: "owner", target: "abu", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.42 },
    { source: "owner", target: "paopao", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.36 },
    { source: "owner", target: "xiaojv", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.3 },
    { source: "owner", target: "yueyue", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.25 },
    { source: "owner", target: "damao", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.2 },
    { source: "owner", target: "tangtang", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.17 },
    { source: "owner", target: "garden", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.14 },
    { source: "owner", target: "heihei", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.11 },
    { source: "owner", target: "beibei", relationKey: "same_owner", displayLabel: "同一主人", weight: 0.09 },
    { source: "owner", target: "mom", relationKey: "family", displayLabel: "家人", weight: 0.88 },
    { source: "owner", target: "dad", relationKey: "family", displayLabel: "家人", weight: 0.8 },
    { source: "owner", target: "xiaoyu", relationKey: "friend", displayLabel: "朋友", weight: 0.75 },
    { source: "owner", target: "alu", relationKey: "friend", displayLabel: "朋友", weight: 0.68 },
    { source: "owner", target: "lin", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.55 },
    { source: "owner", target: "shop", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.45 },
    { source: "owner", target: "wang", relationKey: "friend", displayLabel: "朋友", weight: 0.5 },
    { source: "owner", target: "park", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.35 },
    { source: "owner", target: "cloud", relationKey: "friend", displayLabel: "朋友", weight: 0.3 },
    { source: "owner", target: "neighbor", relationKey: "neighbor", displayLabel: "邻居", weight: 0.25 },
    { source: "owner", target: "aunt", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.22 },
    { source: "owner", target: "xiaolan", relationKey: "friend", displayLabel: "朋友", weight: 0.2 },
    { source: "xiaoyu", target: "xiaohui", relationKey: "friend_elfie", displayLabel: "朋友的精灵", weight: 0.72 },
    { source: "alu", target: "tuantuan", relationKey: "friend_elfie", displayLabel: "朋友的精灵", weight: 0.64 },
    { source: "lin", target: "abu", relationKey: "acquaintance_elfie", displayLabel: "熟人的精灵", weight: 0.45 },
    { source: "wang", target: "paopao", relationKey: "friend_elfie", displayLabel: "朋友的精灵", weight: 0.55 },
    { source: "shop", target: "xiaojv", relationKey: "acquaintance_elfie", displayLabel: "熟人的精灵", weight: 0.38 },
    { source: "park", target: "garden", relationKey: "acquaintance_elfie", displayLabel: "熟人的精灵", weight: 0.28 },
    { source: "cloud", target: "heihei", relationKey: "friend_elfie", displayLabel: "朋友的精灵", weight: 0.22 },
    { source: "aunt", target: "beibei", relationKey: "acquaintance_elfie", displayLabel: "熟人的精灵", weight: 0.16 },
    { source: "xiaolan", target: "yueyue", relationKey: "friend_elfie", displayLabel: "朋友的精灵", weight: 0.25 },
    { source: "mom", target: "dad", relationKey: "family", displayLabel: "家人", weight: 0.8 },
    { source: "xiaoyu", target: "alu", relationKey: "friend", displayLabel: "朋友", weight: 0.4 },
    { source: "xiaoyu", target: "lin", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.3 },
    { source: "park", target: "neighbor", relationKey: "neighbor", displayLabel: "邻居", weight: 0.55 },
    { source: "star", target: "moon", relationKey: "friend", displayLabel: "朋友", weight: 0.62 },
    { source: "moon", target: "doudou", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.35 },
    { source: "mili", target: "xiaohui", relationKey: "friend", displayLabel: "朋友", weight: 0.3 },
    { source: "tangtang", target: "garden", relationKey: "acquaintance", displayLabel: "熟人", weight: 0.2 },
  ],
}
