extends RefCounted

## Wait for Godot's first-run importer and global script scan to finish.
##
## The `.godot/` directory is generated by Godot and intentionally ignored by
## Git.  A headless `--script` process can start before that generated state is
## ready, so loading a scene immediately can report false missing-class and
## missing-import errors.  This helper only observes the generated state; it
## never creates or copies cache files.

const REQUIRED_GLOBAL_CLASSES := ["ModularNest", "ElfieActor"]


static func wait_until_ready(
	tree: SceneTree,
	timeout_seconds: float = 60.0,
) -> bool:
	var timeout_msec := maxi(1, roundi(timeout_seconds * 1000.0))
	var deadline_msec := Time.get_ticks_msec() + timeout_msec
	while Time.get_ticks_msec() < deadline_msec:
		if is_ready():
			return true
		await tree.process_frame
	return is_ready()


static func is_ready() -> bool:
	return _global_script_classes_ready() and _imported_resources_ready()


static func _global_script_classes_ready() -> bool:
	var path := "res://.godot/global_script_class_cache.cfg"
	if not FileAccess.file_exists(path):
		return false
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return false
	var contents := file.get_as_text()
	for required_class in REQUIRED_GLOBAL_CLASSES:
		if not contents.contains('"class": &"%s"' % required_class):
			return false
	return true


static func _imported_resources_ready() -> bool:
	var destinations: Array[String] = []
	_collect_import_destinations("res://", destinations)
	if destinations.is_empty():
		return true
	for destination in destinations:
		if not FileAccess.file_exists(destination):
			return false
	return true


static func _collect_import_destinations(
	path: String,
	destinations: Array[String],
) -> void:
	var directory := DirAccess.open(path)
	if directory == null:
		return
	directory.list_dir_begin()
	while true:
		var entry := directory.get_next()
		if entry.is_empty():
			break
		if entry.begins_with("."):
			continue
		var child_path := path.path_join(entry)
		if directory.current_is_dir():
			_collect_import_destinations(child_path, destinations)
		elif entry.ends_with(".import"):
			_collect_destinations_from_import(child_path, destinations)
	directory.list_dir_end()


static func _collect_destinations_from_import(
	path: String,
	destinations: Array[String],
) -> void:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return
	var contents := file.get_as_text()
	var marker := "dest_files=["
	var marker_start := contents.find(marker)
	if marker_start < 0:
		return
	var values_start := marker_start + marker.length()
	var values_end := contents.find("]", values_start)
	if values_end < 0:
		return
	for raw_value in contents.substr(values_start, values_end - values_start).split(","):
		var destination := raw_value.strip_edges().trim_prefix("\"").trim_suffix("\"")
		if destination.begins_with("res://"):
			destinations.append(destination)
