#!/bin/bash
# Build the publishable curl bootstrap from the canonical native-install helpers.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_PATH="${1:-$SCRIPT_DIR/../dist/install.sh}"
OUTPUT_DIR="${OUTPUT_PATH%/*}"

mkdir -p -- "$OUTPUT_DIR"
{
    printf '%s\n' '#!/bin/bash'
    printf '%s\n' '# Generated by scripts/build_remote_bootstrap.sh; do not edit this release artifact.'
    sed '1{/^#!\/bin\/bash$/d;}' "$SCRIPT_DIR/elfienest_install_helpers.sh"
    sed '1{/^#!\/bin\/bash$/d;}' "$SCRIPT_DIR/native_install_artifact.sh"
    sed '1{/^#!\/bin\/bash$/d;}' "$SCRIPT_DIR/remote_install.sh"
} > "$OUTPUT_PATH"
chmod 0755 "$OUTPUT_PATH"
