"""Exact temporary baseline for known App architecture violations.

The baseline is intentionally executable and reviewed.  It must equal the
current scanner output: remove entries when debt is removed, never add an entry
to make a newly introduced violation pass.
"""

from __future__ import annotations

from typing import Dict, FrozenSet

LEGACY_APP_LAYER_VIOLATIONS: Dict[str, FrozenSet[str]] = {
    "cross_feature_internal_imports": frozenset(
        {
            "app/features/administration/member_service.py -> app.features.accounts.roles",
            "app/features/administration/owner_service.py -> app.features.accounts.password_policy",
            "app/features/adoption/config.py -> app.features.configuration.runtime_store",
        }
    ),
    "feature_forbidden_layer_imports": frozenset(
        {
            "app/features/administration/member_service.py -> app.infrastructure.persistence.interface_query_repository",
            "app/features/administration/owner_service.py -> app.infrastructure.persistence.account_repository",
            "app/features/administration/owner_service.py -> app.infrastructure.persistence.store",
            "app/features/administration/system_service.py -> app.infrastructure.persistence.database_maintenance",
            "app/features/administration/system_service.py -> app.infrastructure.persistence.store",
            "app/features/administration/system_service.py -> app.infrastructure.persistence.system_repository",
            "app/features/adoption/service.py -> app.infrastructure.persistence.account_repository",
            "app/features/adoption/service.py -> app.infrastructure.persistence.elfie_repository",
            "app/features/adoption/service.py -> app.infrastructure.persistence.store",
            "app/features/configuration/food_access.py -> app.infrastructure.persistence.food_assignments",
            "app/features/embodiment/contracts.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/features/setup/install_actions.py -> app.infrastructure.ollama_platform",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.food_packages",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.nest_repository",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.store",
            "app/features/setup/installer.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/ollama.py -> app.infrastructure.ollama_platform",
            "app/features/setup/ollama.py -> app.infrastructure.ollama_platform_commands",
            "app/features/setup/ollama_owner.py -> app.infrastructure.ollama_platform",
            "app/features/setup/ollama_owner.py -> app.infrastructure.ollama_platform_commands",
            "app/features/setup/service.py -> app.infrastructure.persistence.account_repository",
            "app/features/setup/service.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/service.py -> app.infrastructure.persistence.store",
        }
    ),
    "feature_framework_imports": frozenset(
        {
        }
    ),
    "feature_public_db_path": frozenset(
        {
            "app/features/administration/owner_service.py::module.get_owner_account",
            "app/features/administration/owner_service.py::module.recover_owner_account",
            "app/features/administration/system_service.py::module.backup_database",
            "app/features/administration/system_service.py::module.collect_usage_stats",
            "app/features/administration/system_service.py::module.list_active_sessions",
            "app/features/administration/system_service.py::module.list_table_counts",
            "app/features/administration/system_service.py::module.reset_database",
            "app/features/adoption/candidates.py::module.create_candidate_set",
            "app/features/adoption/config.py::module.get_adoption_settings",
            "app/features/adoption/config.py::module.get_allowed_personality_styles",
            "app/features/adoption/config.py::module.get_allowed_species_ids",
            "app/features/adoption/config.py::module.get_max_elfies_per_user",
            "app/features/adoption/service.py::module.adopt_elfie_for_user",
            "app/features/adoption/service.py::module.adoption_options",
            "app/features/adoption/service.py::module.adoption_options_for_user",
            "app/features/configuration/food_access.py::module.elfie_food_policy_projection",
            "app/features/configuration/food_access.py::module.resolve_elfie_food_key",
            "app/features/configuration/food_access.py::module.resolve_elfie_main_food_selection",
            "app/features/configuration/food_access.py::module.visible_food_keys",
            "app/features/setup/install_actions.py::module.run_setup_installation",
            "app/features/setup/installer.py::SetupInstallJobManager.join",
            "app/features/setup/installer.py::SetupInstallJobManager.start",
            "app/features/setup/installer.py::module.build_setup_install_worker",
            "app/features/setup/installer.py::module.recover_interrupted_setup_install",
            "app/features/setup/service.py::module.create_first_owner_from_hash",
            "app/features/setup/service.py::module.has_owner",
            "app/features/setup/service.py::module.needs_setup",
            "app/features/setup/service.py::module.save_offline_setup_draft",
        }
    ),
    "feature_unowned_task_calls": frozenset(
        {
            "app/features/setup/installer.py::start::Thread",
        }
    ),
    "infrastructure_feature_internal_imports": frozenset(
        {
            "app/infrastructure/persistence/interface_query_repository.py -> app.features.accounts.roles",
        }
    ),
    "infrastructure_forbidden_layer_imports": frozenset(),
    "interface_adapter_construction": frozenset(
        {
            "app/interfaces/api/account_auth_routes.py::change_password::RuntimeQueryRepository",
            "app/interfaces/api/account_auth_routes.py::me::RuntimeQueryRepository",
            "app/interfaces/api/account_auth_routes.py::update_profile::RuntimeQueryRepository",
            "app/interfaces/api/account_auth_routes.py::update_theme_preference::RuntimeQueryRepository",
            "app/interfaces/api/app.py::create_http_application::SQLiteFoodPackageRepository",
            "app/interfaces/api/app.py::lifespan::SQLiteNestStateRepository",
            "app/interfaces/api/elfie_food_routes.py::_accessible_elfie::ElfieRepository",
            "app/interfaces/api/elfie_food_routes.py::_projection::SQLiteFoodPackageRepository",
            "app/interfaces/api/food_catalog_support.py::stores::SQLiteFoodPackageRepository",
            "app/interfaces/api/food_catalog_support.py::validated_user_ids::AccountRepository",
            "app/interfaces/api/food_catalog_support.py::validated_user_ids::get_db",
            "app/interfaces/api/food_owner_routes.py::archive_food::SQLiteFoodPackageRepository",
            "app/interfaces/api/food_owner_routes.py::disable_food::SQLiteFoodPackageRepository",
            "app/interfaces/api/food_owner_routes.py::enable_food::SQLiteFoodPackageRepository",
            "app/interfaces/api/food_owner_routes.py::restore_food::SQLiteFoodPackageRepository",
            "app/interfaces/api/observer_routes.py::_owns_elfie::InterfaceQueryRepository",
            "app/interfaces/api/observer_routes.py::_registry::ObserverSessionRegistry",
            "app/interfaces/api/ollama_owner_routes.py::_provider_store::ProviderConnectionStore",
            "app/interfaces/api/owner_elfie_routes.py::_filter_monitoring_rows::SQLiteFoodPackageRepository",
            "app/interfaces/api/owner_elfie_routes.py::_load_registered_elfies::InterfaceQueryRepository",
            "app/interfaces/api/owner_user_routes.py::_load_user::InterfaceQueryRepository",
            "app/interfaces/api/owner_user_routes.py::delete_user::InterfaceQueryRepository",
            "app/interfaces/api/owner_user_routes.py::list_users::InterfaceQueryRepository",
            "app/interfaces/api/owner_user_routes.py::update_quota::InterfaceQueryRepository",
            "app/interfaces/api/owner_user_routes.py::user_avatar::InterfaceQueryRepository",
            "app/interfaces/api/profile_routes.py::current_avatar::InterfaceQueryRepository",
            "app/interfaces/api/profile_routes.py::upload_avatar::InterfaceQueryRepository",
            "app/interfaces/api/setup_routes.py::_require_setup_draft_access::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::_setup_status::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::confirm_setup_install::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::save_setup_nest_draft::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::save_setup_owner_draft::SetupInstallRepository",
            "app/interfaces/api/v1/client_routes.py::_owned_public_profiles::RuntimeQueryRepository",
            "app/interfaces/api/v1/client_routes.py::_owns_elfie::RuntimeQueryRepository",
            "app/interfaces/api/v1/client_routes.py::_private_profile_detail::SQLiteFoodPackageRepository",
            "app/interfaces/api/v1/client_routes.py::update_owner_default_landing_page::RuntimeQueryRepository",
            "app/interfaces/api/v1/device_routes.py::_registry::DeviceRegistry",
            "app/interfaces/api/v1/device_routes.py::_require_owned_elfie::InterfaceQueryRepository",
            "app/interfaces/api/v1/device_routes.py::device_websocket::DeviceRegistry",
            "app/interfaces/api/v1/realtime.py::_owner_id::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_account_id_for_user::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_get_elfie_owner::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_is_elfie_owned_by::RuntimeQueryRepository",
            "app/interfaces/cli/route_commands.py::show_route::ElfieRepository",
        }
    ),
    "interface_feature_internal_imports": frozenset(
        {
            "app/interfaces/api/app.py -> app.features.setup.installer",
            "app/interfaces/api/elfie_food_routes.py -> app.features.configuration.food_access",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama_owner",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama_owner_jobs",
            "app/interfaces/api/owner_elfie_routes.py -> app.features.configuration.food_access",
            "app/interfaces/api/owner_elfie_routes.py -> app.features.elfie_profile.public_projection",
            "app/interfaces/api/owner_user_routes.py -> app.features.accounts.password_policy",
            "app/interfaces/api/owner_user_routes.py -> app.features.accounts.roles",
            "app/interfaces/api/owner_user_routes.py -> app.features.administration.member_service",
            "app/interfaces/api/owner_user_routes.py -> app.features.configuration.runtime_store",
            "app/interfaces/api/page_routes.py -> app.features.setup.service",
            "app/interfaces/api/setup_models.py -> app.features.accounts.password_policy",
            "app/interfaces/api/setup_models.py -> app.features.setup.model_catalog",
            "app/interfaces/api/setup_routes.py -> app.features.setup.hardware",
            "app/interfaces/api/setup_routes.py -> app.features.setup.installer",
            "app/interfaces/api/setup_routes.py -> app.features.setup.model_catalog",
            "app/interfaces/api/setup_routes.py -> app.features.setup.ollama",
            "app/interfaces/api/setup_routes.py -> app.features.setup.service",
            "app/interfaces/api/tool_owner_routes.py -> app.features.configuration.runtime_store",
            "app/interfaces/api/user_routes.py -> app.features.adoption.candidates",
            "app/interfaces/api/user_routes.py -> app.features.adoption.service",
            "app/interfaces/api/v1/client_routes.py -> app.features.configuration.food_access",
            "app/interfaces/api/v1/client_routes.py -> app.features.elfie_profile.public_projection",
            "app/interfaces/cli/lifecycle_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/mobile_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/model_commands.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/model_commands.py -> app.features.configuration.user_config",
            "app/interfaces/cli/owner_commands.py -> app.features.accounts.password_policy",
            "app/interfaces/cli/owner_commands.py -> app.features.administration.owner_service",
            "app/interfaces/cli/provider_commands.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/provider_commands.py -> app.features.configuration.user_config",
            "app/interfaces/cli/runtime_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/tui/config_app.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/config_editors.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/config_views.py -> app.features.administration.system_service",
            "app/interfaces/cli/tui/config_views.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/tui/config_views.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/provider_menu.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/tui/provider_menu.py -> app.features.configuration.user_config",
        }
    ),
    "interface_forbidden_layer_imports": frozenset(
        {
            "app/interfaces/api/account_auth_routes.py -> app.infrastructure.persistence.account_repository",
            "app/interfaces/api/account_auth_routes.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/api/app.py -> app.infrastructure.devices",
            "app/interfaces/api/app.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/app.py -> app.infrastructure.persistence.nest_state_repository",
            "app/interfaces/api/app.py -> app.infrastructure.persistence.store",
            "app/interfaces/api/chat_persistence.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/elfie_food_routes.py -> app.infrastructure.persistence.elfie_repository",
            "app/interfaces/api/elfie_food_routes.py -> app.infrastructure.persistence.food_assignments",
            "app/interfaces/api/elfie_food_routes.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/food_catalog_support.py -> app.infrastructure.persistence.account_repository",
            "app/interfaces/api/food_catalog_support.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/food_catalog_support.py -> app.infrastructure.persistence.store",
            "app/interfaces/api/food_owner_routes.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/observer_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/ollama_owner_models.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/ollama_owner_routes.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/owner_elfie_routes.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/interfaces/api/owner_elfie_routes.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/owner_elfie_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/owner_user_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/profile_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.ollama_platform_commands",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.persistence.setup_install_repository",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.food_packages",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.devices",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.devices.registry",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/v1/realtime.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/v1/realtime.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/api/ws_gateway_messaging.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/cli/route_commands.py -> app.infrastructure.persistence.elfie_repository",
        }
    ),
    "interface_orchestration_internal_imports": frozenset(
        {
            "app/interfaces/cli/doctor_commands.py -> app.orchestration.lifecycle.process",
            "app/interfaces/cli/foreground_runtime.py -> app.orchestration.lifecycle.runtime_health",
            "app/interfaces/cli/foreground_runtime.py -> app.orchestration.lifecycle.types",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.authority",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.helpers",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.process",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.runtime_health",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.runtime_supervisor",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.service",
            "app/interfaces/cli/lifecycle_commands.py -> app.orchestration.lifecycle.types",
            "app/interfaces/cli/owner_commands.py -> app.orchestration.lifecycle.recovery_lock",
        }
    ),
    "json_routes_loose_annotations": frozenset(
        {
            "app/interfaces/api/account_auth_routes.py::change_password::POST /me/password::return:loose",
            "app/interfaces/api/account_auth_routes.py::me::GET /me::return:loose",
            "app/interfaces/api/account_auth_routes.py::update_profile::PUT /me/profile::return:loose",
            "app/interfaces/api/account_auth_routes.py::update_theme_preference::PUT /me/theme::return:loose",
            "app/interfaces/api/app.py::godot_web_status::GET /api/godot-web/status::return:missing",
            "app/interfaces/api/app.py::health::GET /api/health::return:missing",
            "app/interfaces/api/app.py::ws_config::GET /api/ws-config::return:loose",
            "app/interfaces/api/elfie_food_routes.py::get_elfie_main_food::GET /::return:loose",
            "app/interfaces/api/elfie_food_routes.py::update_elfie_main_food::PUT /::parameter:body",
            "app/interfaces/api/elfie_food_routes.py::update_elfie_main_food::PUT /::return:loose",
            "app/interfaces/api/food_owner_routes.py::archive_food::POST /{food_id}/archive::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::archive_food::POST /{food_id}/archive::return:loose",
            "app/interfaces/api/food_owner_routes.py::create_food::POST /::parameter:body",
            "app/interfaces/api/food_owner_routes.py::create_food::POST /::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::create_food::POST /::return:loose",
            "app/interfaces/api/food_owner_routes.py::delete_food::DELETE /{food_id}::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::delete_food::DELETE /{food_id}::return:loose",
            "app/interfaces/api/food_owner_routes.py::disable_food::POST /{food_id}/disable::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::disable_food::POST /{food_id}/disable::return:loose",
            "app/interfaces/api/food_owner_routes.py::edit_food::PUT /{food_id}::parameter:body",
            "app/interfaces/api/food_owner_routes.py::edit_food::PUT /{food_id}::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::edit_food::PUT /{food_id}::return:loose",
            "app/interfaces/api/food_owner_routes.py::enable_food::POST /{food_id}/enable::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::enable_food::POST /{food_id}/enable::return:loose",
            "app/interfaces/api/food_owner_routes.py::list_foods::GET /::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::list_foods::GET /::return:loose",
            "app/interfaces/api/food_owner_routes.py::preview_food_generation::POST /{food_id}/generation-preview::parameter:body",
            "app/interfaces/api/food_owner_routes.py::preview_food_generation::POST /{food_id}/generation-preview::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::preview_food_generation::POST /{food_id}/generation-preview::return:loose",
            "app/interfaces/api/food_owner_routes.py::preview_new_food_generation::POST /generation-preview::parameter:body",
            "app/interfaces/api/food_owner_routes.py::preview_new_food_generation::POST /generation-preview::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::preview_new_food_generation::POST /generation-preview::return:loose",
            "app/interfaces/api/food_owner_routes.py::restore_food::POST /{food_id}/restore::parameter:owner",
            "app/interfaces/api/food_owner_routes.py::restore_food::POST /{food_id}/restore::return:loose",
            "app/interfaces/api/observer_routes.py::next_observer_frame::GET /frames::return:loose",
            "app/interfaces/api/observer_routes.py::open_observer_session::POST /sessions::return:loose",
            "app/interfaces/api/observer_routes.py::submit_observer_intent::POST /intents::return:loose",
            "app/interfaces/api/owner_elfie_routes.py::list_owner_elfie_monitoring::GET /elfies::return:loose",
            "app/interfaces/api/owner_user_routes.py::delete_user::DELETE /{user_id}::return:loose",
            "app/interfaces/api/owner_user_routes.py::list_users::GET ::return:loose",
            "app/interfaces/api/owner_user_routes.py::reset_user_password::POST /{user_id}/reset-password::return:loose",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access::parameter:manager",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access::return:loose",
            "app/interfaces/api/profile_routes.py::upload_avatar::POST /avatar::return:loose",
            "app/interfaces/api/runtime_routes.py::get_runtime_status::GET /status::parameter:owner",
            "app/interfaces/api/runtime_routes.py::get_runtime_status::GET /status::return:loose",
            "app/interfaces/api/setup_routes.py::get_setup_model_catalog::GET /setup/model-catalog::return:loose",
            "app/interfaces/api/setup_routes.py::get_setup_model_recommendation::GET /setup/model-recommendation::parameter:owner",
            "app/interfaces/api/setup_routes.py::get_setup_ollama_detection::GET /setup/ollama-detection::parameter:owner",
            "app/interfaces/api/tool_owner_routes.py::list_tools::GET /::parameter:owner",
            "app/interfaces/api/tool_owner_routes.py::list_tools::GET /::return:loose",
            "app/interfaces/api/tool_owner_routes.py::update_tool::PUT /{tool_key}::parameter:body",
            "app/interfaces/api/tool_owner_routes.py::update_tool::PUT /{tool_key}::parameter:owner",
            "app/interfaces/api/tool_owner_routes.py::update_tool::PUT /{tool_key}::return:loose",
            "app/interfaces/api/tool_owner_routes.py::verify_tool::POST /{tool_key}/verify::parameter:owner",
            "app/interfaces/api/tool_owner_routes.py::verify_tool::POST /{tool_key}/verify::return:loose",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates::parameter:body",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates::return:missing",
            "app/interfaces/api/user_routes.py::adoption_info::GET /adoption-info::return:missing",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies::parameter:body",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies::return:missing",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit::parameter:body",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit::return:missing",
            "app/interfaces/api/v1/client_routes.py::current_client_user::GET /me::return:loose",
            "app/interfaces/api/v1/client_routes.py::list_conversation_messages::GET /conversations/{elfie_id}/messages::return:loose",
            "app/interfaces/api/v1/client_routes.py::list_conversations::GET /conversations::return:loose",
            "app/interfaces/api/v1/client_routes.py::list_public_elfies::GET /elfies::return:loose",
            "app/interfaces/api/v1/client_routes.py::public_elfie_profile::GET /elfies/{elfie_id}/profile::return:loose",
            "app/interfaces/api/v1/client_routes.py::send_conversation_message::POST /conversations/{elfie_id}/messages::return:loose",
            "app/interfaces/api/v1/client_routes.py::update_owner_default_landing_page::PUT /me/default-landing-page::return:loose",
            "app/interfaces/api/v1/device_routes.py::list_devices::GET /owner/devices::return:loose",
        }
    ),
    "json_routes_missing_response_model": frozenset(
        {
            "app/interfaces/api/account_auth_routes.py::change_password::POST /me/password",
            "app/interfaces/api/account_auth_routes.py::me::GET /me",
            "app/interfaces/api/account_auth_routes.py::update_profile::PUT /me/profile",
            "app/interfaces/api/account_auth_routes.py::update_theme_preference::PUT /me/theme",
            "app/interfaces/api/app.py::godot_web_status::GET /api/godot-web/status",
            "app/interfaces/api/app.py::health::GET /api/health",
            "app/interfaces/api/app.py::ws_config::GET /api/ws-config",
            "app/interfaces/api/elfie_food_routes.py::get_elfie_main_food::GET /",
            "app/interfaces/api/elfie_food_routes.py::update_elfie_main_food::PUT /",
            "app/interfaces/api/food_owner_routes.py::archive_food::POST /{food_id}/archive",
            "app/interfaces/api/food_owner_routes.py::create_food::POST /",
            "app/interfaces/api/food_owner_routes.py::delete_food::DELETE /{food_id}",
            "app/interfaces/api/food_owner_routes.py::disable_food::POST /{food_id}/disable",
            "app/interfaces/api/food_owner_routes.py::edit_food::PUT /{food_id}",
            "app/interfaces/api/food_owner_routes.py::enable_food::POST /{food_id}/enable",
            "app/interfaces/api/food_owner_routes.py::list_foods::GET /",
            "app/interfaces/api/food_owner_routes.py::preview_food_generation::POST /{food_id}/generation-preview",
            "app/interfaces/api/food_owner_routes.py::preview_new_food_generation::POST /generation-preview",
            "app/interfaces/api/food_owner_routes.py::restore_food::POST /{food_id}/restore",
            "app/interfaces/api/observer_routes.py::next_observer_frame::GET /frames",
            "app/interfaces/api/observer_routes.py::open_observer_session::POST /sessions",
            "app/interfaces/api/observer_routes.py::submit_observer_intent::POST /intents",
            "app/interfaces/api/observer_routes.py::update_observer_interest::PUT /interest",
            "app/interfaces/api/owner_elfie_routes.py::list_owner_elfie_monitoring::GET /elfies",
            "app/interfaces/api/owner_user_routes.py::create_user::POST ",
            "app/interfaces/api/owner_user_routes.py::delete_user::DELETE /{user_id}",
            "app/interfaces/api/owner_user_routes.py::list_users::GET ",
            "app/interfaces/api/owner_user_routes.py::reset_user_password::POST /{user_id}/reset-password",
            "app/interfaces/api/owner_user_routes.py::update_quota::PUT /{user_id}",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access",
            "app/interfaces/api/profile_routes.py::upload_avatar::POST /avatar",
            "app/interfaces/api/runtime_routes.py::get_runtime_status::GET /status",
            "app/interfaces/api/setup_routes.py::confirm_setup_install::POST /setup/install",
            "app/interfaces/api/setup_routes.py::get_setup_model_catalog::GET /setup/model-catalog",
            "app/interfaces/api/setup_routes.py::get_setup_model_recommendation::GET /setup/model-recommendation",
            "app/interfaces/api/setup_routes.py::get_setup_ollama_detection::GET /setup/ollama-detection",
            "app/interfaces/api/setup_routes.py::get_setup_status::GET /setup-status",
            "app/interfaces/api/setup_routes.py::save_setup_nest_draft::PUT /setup/draft/nest",
            "app/interfaces/api/setup_routes.py::save_setup_offline_draft::PUT /setup/draft/offline",
            "app/interfaces/api/setup_routes.py::save_setup_owner_draft::PUT /setup/draft/owner",
            "app/interfaces/api/tool_owner_routes.py::list_tools::GET /",
            "app/interfaces/api/tool_owner_routes.py::update_tool::PUT /{tool_key}",
            "app/interfaces/api/tool_owner_routes.py::verify_tool::POST /{tool_key}/verify",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates",
            "app/interfaces/api/user_routes.py::adoption_info::GET /adoption-info",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit",
            "app/interfaces/api/v1/client_routes.py::current_client_user::GET /me",
            "app/interfaces/api/v1/client_routes.py::list_conversation_messages::GET /conversations/{elfie_id}/messages",
            "app/interfaces/api/v1/client_routes.py::list_conversations::GET /conversations",
            "app/interfaces/api/v1/client_routes.py::list_public_elfies::GET /elfies",
            "app/interfaces/api/v1/client_routes.py::public_elfie_profile::GET /elfies/{elfie_id}/profile",
            "app/interfaces/api/v1/client_routes.py::send_conversation_message::POST /conversations/{elfie_id}/messages",
            "app/interfaces/api/v1/client_routes.py::update_owner_default_landing_page::PUT /me/default-landing-page",
            "app/interfaces/api/v1/device_routes.py::enroll_device::POST /owner/devices",
            "app/interfaces/api/v1/device_routes.py::list_devices::GET /owner/devices",
            "app/interfaces/api/v1/device_routes.py::revoke_device::DELETE /owner/devices/{body_id}",
            "app/interfaces/api/v1/device_routes.py::rotate_device::POST /owner/devices/{body_id}/rotate",
        }
    ),
    "orchestration_forbidden_layer_imports": frozenset(
        {
            "app/orchestration/embodiment/session_service.py -> app.infrastructure.persistence.embodiment_sessions",
        }
    ),
    "unversioned_product_routes": frozenset(
        {
            "DELETE /api/owner/runtime/foods/{food_id}",
            "DELETE /api/owner/users/{user_id}",
            "GET /api/auth/me",
            "GET /api/auth/me/avatar",
            "GET /api/auth/setup-status",
            "GET /api/auth/setup/model-catalog",
            "GET /api/auth/setup/model-recommendation",
            "GET /api/auth/setup/ollama-detection",
            "GET /api/godot-web/status",
            "GET /api/observer/frames",
            "GET /api/owner/elfies",
            "GET /api/owner/mobile-access",
            "GET /api/owner/providers/ollama",
            "GET /api/owner/runtime/foods/",
            "GET /api/owner/runtime/status",
            "GET /api/owner/runtime/tools/",
            "GET /api/owner/users",
            "GET /api/owner/users/{user_id}/avatar",
            "GET /api/user/adoption-info",
            "GET /api/user/elfies/{elfie_id}/food-policy/",
            "GET /api/ws-config",
            "POST /api/auth/me/avatar",
            "POST /api/auth/me/password",
            "POST /api/auth/setup/install",
            "POST /api/observer/intents",
            "POST /api/observer/sessions",
            "POST /api/owner/providers/ollama/install",
            "POST /api/owner/providers/ollama/models/pull",
            "POST /api/owner/providers/ollama/start",
            "POST /api/owner/runtime/foods/",
            "POST /api/owner/runtime/foods/generation-preview",
            "POST /api/owner/runtime/foods/{food_id}/archive",
            "POST /api/owner/runtime/foods/{food_id}/disable",
            "POST /api/owner/runtime/foods/{food_id}/enable",
            "POST /api/owner/runtime/foods/{food_id}/generation-preview",
            "POST /api/owner/runtime/foods/{food_id}/restore",
            "POST /api/owner/runtime/tools/{tool_key}/verify",
            "POST /api/owner/users",
            "POST /api/owner/users/{user_id}/reset-password",
            "POST /api/user/adoption/candidates",
            "POST /api/user/adoption/commit",
            "POST /api/user/adoption/replies",
            "PUT /api/auth/me/profile",
            "PUT /api/auth/me/theme",
            "PUT /api/auth/setup/draft/nest",
            "PUT /api/auth/setup/draft/offline",
            "PUT /api/auth/setup/draft/owner",
            "PUT /api/observer/interest",
            "PUT /api/owner/runtime/foods/{food_id}",
            "PUT /api/owner/runtime/tools/{tool_key}",
            "PUT /api/owner/users/{user_id}",
            "PUT /api/user/elfies/{elfie_id}/food-policy/",
        }
    ),
}
