"""Exact temporary baseline for known App architecture violations.

The baseline is intentionally executable and reviewed.  It must equal the
current scanner output: remove entries when debt is removed, never add an entry
to make a newly introduced violation pass.
"""

from __future__ import annotations

from typing import Dict, FrozenSet

LEGACY_APP_LAYER_VIOLATIONS: Dict[str, FrozenSet[str]] = {
    "cross_feature_internal_imports": frozenset(
        {
            "app/features/adoption/config.py -> app.features.configuration.runtime_store",
        }
    ),
    "feature_forbidden_layer_imports": frozenset(
        {
            "app/features/adoption/service.py -> app.infrastructure.persistence.account_repository",
            "app/features/adoption/service.py -> app.infrastructure.persistence.elfie_repository",
            "app/features/adoption/service.py -> app.infrastructure.persistence.store",
            "app/features/embodiment/contracts.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/features/setup/install_actions.py -> app.infrastructure.ollama_platform",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.food_packages",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.nest_repository",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/install_actions.py -> app.infrastructure.persistence.store",
            "app/features/setup/installer.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/ollama.py -> app.infrastructure.ollama_platform",
            "app/features/setup/ollama.py -> app.infrastructure.ollama_platform_commands",
            "app/features/setup/ollama_owner.py -> app.infrastructure.ollama_platform",
            "app/features/setup/ollama_owner.py -> app.infrastructure.ollama_platform_commands",
            "app/features/setup/service.py -> app.infrastructure.persistence.account_repository",
            "app/features/setup/service.py -> app.infrastructure.persistence.setup_install_repository",
            "app/features/setup/service.py -> app.infrastructure.persistence.store",
        }
    ),
    "feature_framework_imports": frozenset({}),
    "feature_public_db_path": frozenset(
        {
            "app/features/adoption/candidates.py::module.create_candidate_set",
            "app/features/adoption/config.py::module.get_adoption_settings",
            "app/features/adoption/config.py::module.get_allowed_personality_styles",
            "app/features/adoption/config.py::module.get_allowed_species_ids",
            "app/features/adoption/config.py::module.get_max_elfies_per_user",
            "app/features/adoption/service.py::module.adopt_elfie_for_user",
            "app/features/adoption/service.py::module.adoption_options",
            "app/features/adoption/service.py::module.adoption_options_for_user",
            "app/features/setup/install_actions.py::module.run_setup_installation",
            "app/features/setup/installer.py::SetupInstallJobManager.join",
            "app/features/setup/installer.py::SetupInstallJobManager.start",
            "app/features/setup/installer.py::module.build_setup_install_worker",
            "app/features/setup/installer.py::module.recover_interrupted_setup_install",
            "app/features/setup/service.py::module.create_first_owner_from_hash",
            "app/features/setup/service.py::module.has_owner",
            "app/features/setup/service.py::module.needs_setup",
            "app/features/setup/service.py::module.save_offline_setup_draft",
        }
    ),
    "feature_unowned_task_calls": frozenset(
        {
            "app/features/setup/installer.py::start::Thread",
        }
    ),
    "infrastructure_feature_internal_imports": frozenset({}),
    "infrastructure_forbidden_layer_imports": frozenset(),
    "interface_adapter_construction": frozenset(
        {
            "app/interfaces/api/app.py::lifespan::SQLiteNestStateRepository",
            "app/interfaces/api/observer_routes.py::_owns_elfie::InterfaceQueryRepository",
            "app/interfaces/api/observer_routes.py::_registry::ObserverSessionRegistry",
            "app/interfaces/api/ollama_owner_routes.py::_provider_store::ProviderConnectionStore",
            "app/interfaces/api/owner_elfie_routes.py::_load_registered_elfies::InterfaceQueryRepository",
            "app/interfaces/api/setup_routes.py::_require_setup_draft_access::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::_setup_status::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::confirm_setup_install::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::save_setup_nest_draft::SetupInstallRepository",
            "app/interfaces/api/setup_routes.py::save_setup_owner_draft::SetupInstallRepository",
            "app/interfaces/api/v1/client_routes.py::_owned_public_profiles::RuntimeQueryRepository",
            "app/interfaces/api/v1/client_routes.py::_owns_elfie::RuntimeQueryRepository",
            "app/interfaces/api/v1/device_routes.py::_registry::DeviceRegistry",
            "app/interfaces/api/v1/device_routes.py::_require_owned_elfie::InterfaceQueryRepository",
            "app/interfaces/api/v1/device_routes.py::device_websocket::DeviceRegistry",
            "app/interfaces/api/v1/realtime.py::_owner_id::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_account_id_for_user::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_get_elfie_owner::RuntimeQueryRepository",
            "app/interfaces/api/ws_gateway_messaging.py::_is_elfie_owned_by::RuntimeQueryRepository",
            "app/interfaces/cli/route_commands.py::show_route::ElfieRepository",
        }
    ),
    "interface_feature_internal_imports": frozenset(
        {
            "app/interfaces/api/app.py -> app.features.setup.installer",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama_owner",
            "app/interfaces/api/ollama_owner_routes.py -> app.features.setup.ollama_owner_jobs",
            "app/interfaces/api/owner_elfie_routes.py -> app.features.elfie_profile.public_projection",
            "app/interfaces/api/page_routes.py -> app.features.setup.service",
            "app/interfaces/api/setup_models.py -> app.features.accounts.password_policy",
            "app/interfaces/api/setup_models.py -> app.features.setup.model_catalog",
            "app/interfaces/api/setup_routes.py -> app.features.setup.hardware",
            "app/interfaces/api/setup_routes.py -> app.features.setup.installer",
            "app/interfaces/api/setup_routes.py -> app.features.setup.model_catalog",
            "app/interfaces/api/setup_routes.py -> app.features.setup.ollama",
            "app/interfaces/api/setup_routes.py -> app.features.setup.service",
            "app/interfaces/api/user_routes.py -> app.features.adoption.candidates",
            "app/interfaces/api/user_routes.py -> app.features.adoption.service",
            "app/interfaces/api/v1/client_routes.py -> app.features.elfie_profile.public_projection",
            "app/interfaces/cli/lifecycle_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/mobile_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/model_commands.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/model_commands.py -> app.features.configuration.user_config",
            "app/interfaces/cli/provider_commands.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/provider_commands.py -> app.features.configuration.user_config",
            "app/interfaces/cli/runtime_commands.py -> app.features.administration.system_service",
            "app/interfaces/cli/tui/config_app.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/config_editors.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/config_views.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/tui/config_views.py -> app.features.configuration.user_config",
            "app/interfaces/cli/tui/provider_menu.py -> app.features.configuration.provider_service",
            "app/interfaces/cli/tui/provider_menu.py -> app.features.configuration.user_config",
        }
    ),
    "interface_forbidden_layer_imports": frozenset(
        {
            "app/interfaces/api/app.py -> app.infrastructure.devices",
            "app/interfaces/api/app.py -> app.infrastructure.persistence.nest_state_repository",
            "app/interfaces/api/app.py -> app.infrastructure.persistence.store",
            "app/interfaces/api/chat_persistence.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/observer_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/ollama_owner_models.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/ollama_owner_routes.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/owner_elfie_routes.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/interfaces/api/owner_elfie_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.ollama_platform",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.ollama_platform_commands",
            "app/interfaces/api/setup_routes.py -> app.infrastructure.persistence.setup_install_repository",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.embodiment_sessions",
            "app/interfaces/api/v1/client_routes.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.devices",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.devices.registry",
            "app/interfaces/api/v1/device_routes.py -> app.infrastructure.persistence.interface_query_repository",
            "app/interfaces/api/v1/realtime.py -> app.infrastructure.persistence.elfie_chat_history",
            "app/interfaces/api/v1/realtime.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/api/ws_gateway_messaging.py -> app.infrastructure.persistence.runtime_query_repository",
            "app/interfaces/cli/route_commands.py -> app.infrastructure.persistence.elfie_repository",
        }
    ),
    "interface_orchestration_internal_imports": frozenset(),
    "json_routes_loose_annotations": frozenset(
        {
            "app/interfaces/api/app.py::godot_web_status::GET /api/godot-web/status::return:missing",
            "app/interfaces/api/app.py::health::GET /api/health::return:missing",
            "app/interfaces/api/app.py::ws_config::GET /api/ws-config::return:loose",
            "app/interfaces/api/observer_routes.py::next_observer_frame::GET /frames::return:loose",
            "app/interfaces/api/observer_routes.py::open_observer_session::POST /sessions::return:loose",
            "app/interfaces/api/observer_routes.py::submit_observer_intent::POST /intents::return:loose",
            "app/interfaces/api/owner_elfie_routes.py::list_owner_elfie_monitoring::GET /elfies::return:loose",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access::parameter:manager",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access::return:loose",
            "app/interfaces/api/setup_routes.py::get_setup_model_catalog::GET /setup/model-catalog::return:loose",
            "app/interfaces/api/setup_routes.py::get_setup_model_recommendation::GET /setup/model-recommendation::parameter:owner",
            "app/interfaces/api/setup_routes.py::get_setup_ollama_detection::GET /setup/ollama-detection::parameter:owner",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates::parameter:body",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates::return:missing",
            "app/interfaces/api/user_routes.py::adoption_info::GET /adoption-info::return:missing",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies::parameter:body",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies::return:missing",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit::parameter:body",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit::return:missing",
            "app/interfaces/api/v1/client_routes.py::list_conversation_messages::GET /conversations/{elfie_id}/messages::return:loose",
            "app/interfaces/api/v1/client_routes.py::list_conversations::GET /conversations::return:loose",
            "app/interfaces/api/v1/client_routes.py::list_public_elfies::GET /elfies::return:loose",
            "app/interfaces/api/v1/client_routes.py::public_elfie_profile::GET /elfies/{elfie_id}/profile::return:loose",
            "app/interfaces/api/v1/client_routes.py::send_conversation_message::POST /conversations/{elfie_id}/messages::return:loose",
            "app/interfaces/api/v1/device_routes.py::list_devices::GET /owner/devices::return:loose",
        }
    ),
    "json_routes_missing_response_model": frozenset(
        {
            "app/interfaces/api/app.py::godot_web_status::GET /api/godot-web/status",
            "app/interfaces/api/app.py::health::GET /api/health",
            "app/interfaces/api/app.py::ws_config::GET /api/ws-config",
            "app/interfaces/api/observer_routes.py::next_observer_frame::GET /frames",
            "app/interfaces/api/observer_routes.py::open_observer_session::POST /sessions",
            "app/interfaces/api/observer_routes.py::submit_observer_intent::POST /intents",
            "app/interfaces/api/observer_routes.py::update_observer_interest::PUT /interest",
            "app/interfaces/api/owner_elfie_routes.py::list_owner_elfie_monitoring::GET /elfies",
            "app/interfaces/api/page_routes.py::owner_mobile_access::GET /api/owner/mobile-access",
            "app/interfaces/api/setup_routes.py::confirm_setup_install::POST /setup/install",
            "app/interfaces/api/setup_routes.py::get_setup_model_catalog::GET /setup/model-catalog",
            "app/interfaces/api/setup_routes.py::get_setup_model_recommendation::GET /setup/model-recommendation",
            "app/interfaces/api/setup_routes.py::get_setup_ollama_detection::GET /setup/ollama-detection",
            "app/interfaces/api/setup_routes.py::get_setup_status::GET /setup-status",
            "app/interfaces/api/setup_routes.py::save_setup_nest_draft::PUT /setup/draft/nest",
            "app/interfaces/api/setup_routes.py::save_setup_offline_draft::PUT /setup/draft/offline",
            "app/interfaces/api/setup_routes.py::save_setup_owner_draft::PUT /setup/draft/owner",
            "app/interfaces/api/user_routes.py::adoption_candidates::POST /adoption/candidates",
            "app/interfaces/api/user_routes.py::adoption_info::GET /adoption-info",
            "app/interfaces/api/user_routes.py::adoption_replies::POST /adoption/replies",
            "app/interfaces/api/user_routes.py::commit_adoption::POST /adoption/commit",
            "app/interfaces/api/v1/client_routes.py::list_conversation_messages::GET /conversations/{elfie_id}/messages",
            "app/interfaces/api/v1/client_routes.py::list_conversations::GET /conversations",
            "app/interfaces/api/v1/client_routes.py::list_public_elfies::GET /elfies",
            "app/interfaces/api/v1/client_routes.py::public_elfie_profile::GET /elfies/{elfie_id}/profile",
            "app/interfaces/api/v1/client_routes.py::send_conversation_message::POST /conversations/{elfie_id}/messages",
            "app/interfaces/api/v1/device_routes.py::enroll_device::POST /owner/devices",
            "app/interfaces/api/v1/device_routes.py::list_devices::GET /owner/devices",
            "app/interfaces/api/v1/device_routes.py::revoke_device::DELETE /owner/devices/{body_id}",
            "app/interfaces/api/v1/device_routes.py::rotate_device::POST /owner/devices/{body_id}/rotate",
        }
    ),
    "orchestration_forbidden_layer_imports": frozenset(
        {
            "app/orchestration/embodiment/session_service.py -> app.infrastructure.persistence.embodiment_sessions",
        }
    ),
    "unversioned_product_routes": frozenset(
        {
            "GET /api/auth/setup-status",
            "GET /api/auth/setup/model-catalog",
            "GET /api/auth/setup/model-recommendation",
            "GET /api/auth/setup/ollama-detection",
            "GET /api/godot-web/status",
            "GET /api/observer/frames",
            "GET /api/owner/elfies",
            "GET /api/owner/mobile-access",
            "GET /api/owner/providers/ollama",
            "GET /api/user/adoption-info",
            "GET /api/ws-config",
            "POST /api/auth/setup/install",
            "POST /api/observer/intents",
            "POST /api/observer/sessions",
            "POST /api/owner/providers/ollama/install",
            "POST /api/owner/providers/ollama/models/pull",
            "POST /api/owner/providers/ollama/start",
            "POST /api/user/adoption/candidates",
            "POST /api/user/adoption/commit",
            "POST /api/user/adoption/replies",
            "PUT /api/auth/setup/draft/nest",
            "PUT /api/auth/setup/draft/offline",
            "PUT /api/auth/setup/draft/owner",
            "PUT /api/observer/interest",
        }
    ),
}
